version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: quiz_postgres
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - quiz-net

  auth-service:
    build: ./auth-service
    container_name: auth_service
    env_file: ./auth-service/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "50051:50051"
    networks:
      - quiz-net

volumes:
  pgdata:

networks:
  quiz-net:
    driver: bridge
