syntax = "proto3";

package match;

service MatchService {
  rpc CreateMatchRequest (CreateMatchRequest) returns (CreatedMatchResponse);
  rpc GetMatchStatusResponse (GetStatusRequest) returns (MatchStatusResponse);
  rpc Answer (AnswerRequest) returns (AnswerResponse);
  rpc GetMatchRanking (MatchRankingRequest) returns (MatchRankingResponse);
}

message GeneratedQuestion {
  string statement = 1;
  map<string, string> alternatives = 2;
  string correctAnswer = 3;
}

message CreateMatchRequest {
  int32 userId = 1;
  repeated GeneratedQuestion questions = 2;
  repeated int32 userPlayersIds = 3;
  string difficulty = 4;
  string topic = 5;
}

message CreatedMatchResponse {
  int32 currentRound = 1;
  int32 totalRounds = 2;
  repeated int32 userPlayersIds = 3;
  string difficulty = 4;
  string topic = 5;
}

message GetStatusRequest {
  int32 userId = 1;
  string roomName = 2;
}

message MatchStatusResponse {
  int32 currentRound = 1;
  string timer = 2;
  string difficulty = 3;
  string topic = 4;
  MatchQuestion question = 5;
}

message MatchQuestion {
  string statement = 1;
  map<string, string> alternatives = 2;
  repeated int32 userAnswerersIds = 3;
}

message AnswerRequest {
  string roomName = 1;
  int32 userId = 2;
  string answer = 3;
}

message AnswerResponse {
  bool isRight = 1;
}

message MatchRankingRequest {
  string roomName = 1;
  int32 userId = 2;
}

message MatchRankingResponse {
  repeated UserRanking userRankings = 1;
}

message UserRanking {
  int32 userId = 1;
  int64 score = 2;
}
