syntax = "proto3";

package room;

service RoomService {
  rpc CreateRoom(CreateRoomRequest) returns (RoomResponse);
  rpc JoinRoom(JoinRoomRequest) returns (RoomResponse);
  rpc LeaveRoom(LeaveRoomRequest) returns (RoomResponse);
  rpc GetRooms(Empty) returns (RoomsList);
  rpc ListPlayers(ListPlayersRequest) returns (PlayersList);

  rpc Ping(Empty) returns (PingResponse);
}

message CreateRoomRequest {
  string name = 1;
  string ownerId = 2;
}

message JoinRoomRequest {
  string roomId = 1;
  string playerId = 2;
  string playerName = 3;
}

message Player {
  string id = 1;
  string name = 2;
}

message LeaveRoomRequest {
  string roomId = 1;
  string playerId = 2;
}

message ListPlayersRequest {
  string roomId = 1;
}

message RoomsList {
  repeated RoomResponse rooms = 1;
}

message RoomResponse {
  string id = 1;
  string name = 2;
  string ownerId = 3;
  string status = 4;
  repeated Player players = 5;
}

message PlayersList {
  repeated Player players = 1;
}

message Empty {}

message PingResponse {
  string message = 1;
}
