syntax = "proto3";

package room;

service RoomService {
  rpc CreateRoom (UserRoomRequest) returns (RoomStatusResponse);
  rpc EnterRoom (UserRoomRequest) returns (RoomStatusResponse);
  rpc StartMatch (StartMatchRequest) returns (MatchStatusResponse);
}

message UserRoomRequest {
  string roomName = 1;
  int32 userId = 2;
}

message RoomStatusResponse {
  int32 id = 1;
  string name = 2;
  string status = 3;
  int32 userOwnerId = 4;
  repeated int32 userPlayersId = 5;
  int32 matchQtd = 6;
}

message StartMatchRequest {
  int32 userId = 1;
  string roomName = 2;
  string topic = 3;
  string difficulty = 4;
}

message MatchStatusResponse {
  int32 currentRound = 1;
  repeated int32 userPlayersId = 2;
  string topic = 3;
  string difficulty = 4;
}